version: '3.9'

services:
  tracing:
    extends:
      file: common.yml
      service: common
    container_name: tracing_ui
    image: jaegertracing/all-in-one:1.40
    depends_on:
      elasticsearch: # Disable this if you are using an external ElasticSearch database
        condition: service_healthy
    expose:
      - 14268
      - 16686
      - 14250
    environment:
      COLLECTOR_OTLP_ENABLED: true
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: ${ELASTICSEARCH_URI}
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - tracing.turnly.local
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      - traefik.http.routers.tracing-public.entrypoints=tracing
      - traefik.http.routers.tracing-public.service=tracing-public
      - traefik.http.routers.tracing-public.rule=Host(`${APP_INFRA_DOMAIN}`)
      - traefik.http.services.tracing-public.loadbalancer.server.port=16686

      # Attach the OAuth-middleware to this service
      - traefik.http.routers.tracing-public.middlewares=oauth-admin-middleware
