name: ğŸ”¦ CI - Linters

on:
  pull_request:
    paths:
      - apps/**
    branches:
      - develop
      - main

  push:
    paths:
      - apps/**
      - .github/workflows/global-continuous-integration-linters.yml
    branches:
      - develop
      - main

jobs:
  code:
    name: ğŸ”¦ Lint code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12]
        mongodb-version: [5.0.9]

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸš€ Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ”¦ Lint all
        run: yarn devo lint --all

  commits:
    name: ğŸ”¦ Lint Commits Messages
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v3

  pr_title:
    if: ${{ github.event_name == 'pull_request' }}
    name: ğŸ”¦ Lint PR Title
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
            improvement
            improve
