name: Lint code

on: [push, pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸš€ Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: ğŸ“¦ Install Dependencies
        run: yarn install --immutable --immutable-cache

      - name: ğŸ”— Copying environment variables
        run: |
          cp .env.example .env

      - name: ğŸ”¦ Run linters on each app
        run: |
          yarn devo lint --all
