name: ğŸ”¦ Lint code

on: [push, pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸš€ Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ”¦ Run linters on each app
        run: |
          yarn devo lint --all
