name: Queuing System Test Suite

on:
  pull_request:
    paths:
      - 'apps/queuing-system/**'
  push:
    paths:
      - '.github/workflows/queuing-system-tests.yml'
      - 'apps/queuing-system/**'
    branches:
      - develop
      - main

env:
  MONGO_DB: turnly_testing_db
  MONGO_USERNAME: root
  MONGO_PASSWORD: turnly

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]
        mongodb-version: [latest]

    services:
      mongo:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_PASSWORD }}
        options: >-
          --name mongo
          --hostname mongo
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ”‹ Run the unit tests
        run: yarn devo queuing-system test:unit

      - name: ğŸ’Š Setting integration tests dependencies...
        uses: ./.github/actions/setup-mongodb
        with:
          mongo-username: ${{ env.MONGO_USERNAME }}
          mongo-password: ${{ env.MONGO_PASSWORD }}
          mongo-db: ${{ env.MONGO_DB }}

      - name: ğŸ”‹ Run the integration tests
        run: yarn devo queuing-system test:integration
