name: ğŸ”‹ Queuing System Test Suites

on:
  pull_request:
    paths:
      - 'apps/queuing-system/**'
  push:
    paths:
      - '.github/workflows/queuing-system-tests.yml'
      - 'apps/queuing-system/**'
    branches:
      - develop
      - main

env:
  MONGO_DB: turnly_testing_db
  MONGO_USERNAME: root
  MONGO_PASSWORD: turnly

jobs:
  unit_and_integration:
    name: ğŸ§© Unit & Integration
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15]
        mongodb-version: [latest]

    services:
      mongo:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_PASSWORD }}
        options: >-
          --name mongo
          --hostname mongo
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸš€ Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ§ª Run the unit tests
        run: yarn devo queuing-system test:unit

      - name: ğŸ’Š Setting integration tests dependencies...
        uses: ./.github/actions/setup-mongodb
        with:
          mongo-username: ${{ env.MONGO_USERNAME }}
          mongo-password: ${{ env.MONGO_PASSWORD }}
          mongo-db: ${{ env.MONGO_DB }}

      - name: ğŸ§ª Run the integration tests
        run: yarn devo queuing-system test:integration

  e2e_and_benchmark:
    name: ğŸ§© E2E & Benchmark
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15]
        mongodb-version: [latest]

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸš€ Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ“¦ Pull base dependencies
        run: |
          docker pull node:${{ matrix.node-version }}-alpine3.15

      - name: ğŸš€ Start application
        run: |
          yarn devo start -s queuing-system --verbose

      - name: ğŸ§ª Run the e2e tests
        run: yarn devo queuing-system test:e2e

      - name: ğŸ§ª Run the benchmark tests
        run: yarn devo queuing-system test:benchmark

      - name: ğŸ”¥ Teardown
        if: always()
        run: |
          yarn devo stop --verbose
          docker system prune -fa
