name: Queuing System Test Suite

on:
  pull_request:
    paths:
      - 'apps/queuing-system/**'
  push:
    paths:
      - '.github/workflows/queuing-system-tests.yml'
      - 'apps/queuing-system/**'
    branches:
      - develop
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]
        mongodb-version: [latest]

    services:
      mongo:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: turnly
          MONGO_INITDB_DATABASE: turnly_testing_db
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸš€ Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: ğŸ“¦ Install Dependencies
        run: yarn install --immutable --immutable-cache

      - name: ğŸ”— Copying environment variables
        run: cp .env.example .env

      - name: ğŸ”¦ Lint code
        run: |
          yarn workspace @turnly/queuing-system lint:format
          yarn workspace @turnly/queuing-system lint:check
          yarn workspace @turnly/queuing-system lint:ts:check

      - name: ğŸ”‹ Run the unit tests
        run: yarn devo queuing-system test:unit

      - name: ğŸ”‹ Run the integration tests
        run: yarn devo queuing-system test:integration
