name: ğŸ”‹ Test Suites

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

env:
  MONGO_DB: turnly_testing_db
  MONGO_USERNAME: root
  MONGO_PASSWORD: turnly

jobs:
  unit_and_integration:
    name: ğŸ§© Unit & Integration
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15]
        mongodb-version: [latest]

    services:
      mongo:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_PASSWORD }}
        options: >-
          --name mongo
          --hostname mongo
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/filters.yml

      - name: ğŸš€ Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ’Š Setting integration tests dependencies...
        uses: ./.github/actions/setup-mongodb
        with:
          mongo-username: ${{ env.MONGO_USERNAME }}
          mongo-password: ${{ env.MONGO_PASSWORD }}
          mongo-db: ${{ env.MONGO_DB }}

      - name: "ğŸ§ª Add-ons: run unit tests"
        if: steps.filter.outputs.addons == 'true'
        run: yarn devo addons test:unit

      - name: "ğŸ§ª Add-ons: run integration tests"
        if: steps.filter.outputs.addons == 'true'
        run: yarn devo addons test:integration

      - name: "ğŸ§ª Assistance Centers: run unit tests"
        if: steps.filter.outputs.assistance-centers == 'true'
        run: yarn devo assistance-centers test:unit

      - name: "ğŸ§ª Assistance Centers: run integration tests"
        if: steps.filter.outputs.assistance-centers == 'true'
        run: yarn devo assistance-centers test:integration

      - name: "ğŸ§ª Business Owners: run unit tests"
        if: steps.filter.outputs.business-owners == 'true'
        run: yarn devo business-owners test:unit

      - name: "ğŸ§ª Business Owners: run integration tests"
        if: steps.filter.outputs.business-owners == 'true'
        run: yarn devo business-owners test:integration

      - name: "ğŸ§ª Custom Fields: run unit tests"
        if: steps.filter.outputs.custom-fields == 'true'
        run: yarn devo custom-fields test:unit

      - name: "ğŸ§ª Custom Fields: run integration tests"
        if: steps.filter.outputs.custom-fields == 'true'
        run: yarn devo custom-fields test:integration

      - name: "ğŸ§ª Queuing System: run unit tests"
        if: steps.filter.outputs.queuing-system == 'true'
        run: yarn devo queuing-system test:unit

      - name: "ğŸ§ª Queuing System: run integration tests"
        if: steps.filter.outputs.queuing-system == 'true'
        run: yarn devo queuing-system test:integration

      - name: "ğŸ§ª Teams: run unit tests"
        if: steps.filter.outputs.teams == 'true'
        run: yarn devo teams test:unit

      - name: "ğŸ§ª Teams: run integration tests"
        if: steps.filter.outputs.teams == 'true'
        run: yarn devo teams test:integration

  e2e_and_benchmark:
    name: ğŸ§© E2E & Benchmark
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15]
        mongodb-version: [latest]

    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸ•’ Please wait, the next step will take a few minutes...
        run: echo "..."

      - name: ğŸ³ Setup the environment
        uses: ./.github/actions/setup-docker-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸš€ Start all applications
        run: yarn devo start --verbose

      - name: ğŸ Wait for the infrastructure to get up
        uses: ./.github/actions/wait-for-infrastructure

      - name: "ğŸ§ª Add-ons: run e2e tests"
        if: steps.filter.outputs.addons == 'true'
        run: yarn devo addons test:e2e

      - name: "ğŸ§ª Add-ons: run benchmark tests"
        if: steps.filter.outputs.addons == 'true'
        run: yarn devo addons test:benchmark

      - name: "ğŸ§ª Assistance Centers: run e2e tests"
        if: steps.filter.outputs.assistance-centers == 'true'
        run: yarn devo assistance-centers test:e2e

      - name: "ğŸ§ª Assistance Centers: run benchmark tests"
        if: steps.filter.outputs.assistance-centers == 'true'
        run: yarn devo assistance-centers test:benchmark

      - name: "ğŸ§ª Business Owners: run e2e tests"
        if: steps.filter.outputs.business-owners == 'true'
        run: yarn devo business-owners test:e2e

      - name: "ğŸ§ª Business Owners: run benchmark tests"
        if: steps.filter.outputs.business-owners == 'true'
        run: yarn devo business-owners test:benchmark

      - name: "ğŸ§ª Custom Fields: run e2e tests"
        if: steps.filter.outputs.custom-fields == 'true'
        run: yarn devo custom-fields test:e2e

      - name: "ğŸ§ª Custom Fields: run benchmark tests"
        if: steps.filter.outputs.custom-fields == 'true'
        run: yarn devo custom-fields test:benchmark

      - name: "ğŸ§ª Queuing System: run e2e tests"
        if: steps.filter.outputs.queuing-system == 'true'
        run: yarn devo queuing-system test:e2e

      - name: "ğŸ§ª Queuing System: run benchmark tests"
        if: steps.filter.outputs.queuing-system == 'true'
        run: yarn devo queuing-system test:benchmark

      - name: "ğŸ§ª Teams: run e2e tests"
        if: steps.filter.outputs.teams == 'true'
        run: yarn devo teams test:e2e

      - name: "ğŸ§ª Teams: run benchmark tests"
        if: steps.filter.outputs.teams == 'true'
        run: yarn devo teams test:benchmark

      - name: ğŸ”¥ Teardown
        if: always()
        run: |
          yarn devo stop --verbose
          docker system prune -fa
